title: Praveen Kumar A
logo: /assets/img/logo.png
description: This POC is for capturing the trends of data processed for the day and to get the completion status of
the job. This monitoring was done manually before, but after this POC it was automated and helps in
fine tuning the spark job.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
